## Preprocessing

In [1]:
!pip install keras-tuner

Requirement already satisfied: keras-tuner in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (1.1.0)
Requirement already satisfied: scipy in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from keras-tuner) (1.7.3)
Requirement already satisfied: requests in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from keras-tuner) (2.27.1)
Requirement already satisfied: kt-legacy in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from keras-tuner) (1.0.4)
Requirement already satisfied: numpy in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from keras-tuner) (1.22.2)
Requirement already satisfied: ipython in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from keras-tuner) (7.31.1)
Requirement already satisfied: tensorboard in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from keras-tuner) (2.8.0)
Requirement already satisfied: packaging in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from keras-tuner) (21.3)
Requirement already satisfied: pygments in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (2.11.2)
Requirement already satisfied: pickleshare in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (0.7.5)
Requirement already satisfied: decorator in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (5.1.1)
Requirement already satisfied: backcall in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (0.2.0)
Requirement already satisfied: matplotlib-inline in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (0.1.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (3.0.20)
Requirement already satisfied: setuptools>=18.5 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (58.0.4)
Requirement already satisfied: traitlets>=4.2 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (0.18.1)
Requirement already satisfied: appnope in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (0.1.2)
Requirement already satisfied: pexpect>4.3 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from ipython->keras-tuner) (4.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from jedi>=0.16->ipython->keras-tuner) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from pexpect>4.3->ipython->keras-tuner) (0.7.0)
Requirement already satisfied: wcwidth in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->keras-tuner) (0.2.5)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from packaging->keras-tuner) (3.0.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from requests->keras-tuner) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from requests->keras-tuner) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from requests->keras-tuner) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from requests->keras-tuner) (2021.10.8)
Requirement already satisfied: google-auth<3,>=1.6.3 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (2.6.0)
Requirement already satisfied: wheel>=0.26 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (0.37.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (0.6.1)
Requirement already satisfied: absl-py>=0.4 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (1.0.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (1.8.1)
Requirement already satisfied: protobuf>=3.6.0 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (3.19.4)
Requirement already satisfied: markdown>=2.6.8 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (3.3.6)
Requirement already satisfied: werkzeug>=0.11.15 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (2.0.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (0.4.6)
Requirement already satisfied: grpcio>=1.24.3 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from tensorboard->keras-tuner) (1.44.0)
Requirement already satisfied: six in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from absl-py>=0.4->tensorboard->keras-tuner) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (4.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (5.0.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->keras-tuner) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from markdown>=2.6.8->tensorboard->keras-tuner) (4.8.2)
Requirement already satisfied: zipp>=0.5 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->keras-tuner) (3.7.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->keras-tuner) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /Users/dan/opt/anaconda3/envs/PythonData/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->keras-tuner) (3.2.0)

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN", "NAME"])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column
# (https://stackoverflow.com/questions/56310788/different-outcome-using-pandas-nunique-and-unique)
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
app_count = application_df["APPLICATION_TYPE"].value_counts()
app_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_count[app_count < 500].index)
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [7]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
class_count = application_df["CLASSIFICATION"].value_counts()
class_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_count_1 = class_count[class_count > 1]
class_count_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_count[class_count < 100].index)
classifications_to_replace

['C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256',
 'C2190',
 'C4200',
 'C2600',
 'C5200',
 'C1370',
 'C1248',
 'C6100',
 'C1820',
 'C1900',
 'C1236',
 'C3700',
 'C2570',
 'C1580',
 'C1245',
 'C2500',
 'C1570',
 'C1283',
 'C2380',
 'C1732',
 'C1728',
 'C2170',
 'C4120',
 'C8210',
 'C2561',
 'C4500',
 'C2150']

In [11]:
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_df = pd.get_dummies(application_df)
numeric_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
# target: IS_SUCCESSFUL, features: everything else
y = numeric_df["IS_SUCCESSFUL"]
X = numeric_df.drop(["IS_SUCCESSFUL"], axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
number_input_features = len(X_train_scaled[0])
number_input_features

49

In [16]:
# (borrowed from 21.2, activity 4)
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=30,
        step=5), activation=activation, input_dim=number_input_features))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=30,
            step=5),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [17]:
# Import the kerastuner library (for optimizing model)
import kerastuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

/var/folders/6j/g7z_h15n2xb6lf5plnw73lrm0000gn/T/ipykernel_86584/2542971318.py:2: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [18]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 60 Complete [00h 01m 28s]
val_accuracy: 0.7327113747596741

Best val_accuracy So Far: 0.73399418592453
Total elapsed time: 00h 25m 15s
INFO:tensorflow:Oracle triggered exit

In [21]:
optimal_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
optimal_hps

In [24]:
# retrieve optimal hyperparameters
# (https://www.tensorflow.org/tutorials/keras/keras_tuner)
optimal_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

print(f"Optimal number of units in first layer: {optimal_hps.get('first_units')}")
print(f"Number of layers: {optimal_hps.get('num_layers')}")
print(f"Optimal activation: {optimal_hps.get('activation')}")

Optimal number of units in first layer: 11
Number of layers: 4
Optimal activation: tanh

In [26]:
# find optimal number of epochs by building model with optimal hyperparameters we found
model = tuner.hypermodel.build(optimal_hps)
history = model.fit(X_train_scaled, y_train, epochs=50, validation_data=(X_test_scaled,y_test))

val_acc_per_epoch = history.history['val_accuracy']
optimal_epoch = val_acc_per_epoch.index(max(val_acc_per_epoch)) + 1
print("Optimal number of epochs: %d" % (optimal_epoch))

Epoch 1/50
804/804 [==============================] - 7s 7ms/step - loss: 0.5951 - accuracy: 0.7002 - val_loss: 0.5657 - val_accuracy: 0.7233
Epoch 2/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5626 - accuracy: 0.7251 - val_loss: 0.5617 - val_accuracy: 0.7270
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5572 - accuracy: 0.7269 - val_loss: 0.5567 - val_accuracy: 0.7303
Epoch 4/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5548 - accuracy: 0.7308 - val_loss: 0.5580 - val_accuracy: 0.7318
Epoch 5/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5530 - accuracy: 0.7297 - val_loss: 0.5569 - val_accuracy: 0.7284
Epoch 6/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5517 - accuracy: 0.7321 - val_loss: 0.5542 - val_accuracy: 0.7313
Epoch 7/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5502 - accuracy: 0.7307 - val_loss: 0.5538 - val_accuracy: 0.7325
Epoch 8/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5497 - accuracy: 0.7315 - val_loss: 0.5532 - val_accuracy: 0.7286
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5488 - accuracy: 0.7322 - val_loss: 0.5547 - val_accuracy: 0.7285
Epoch 10/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5480 - accuracy: 0.7318 - val_loss: 0.5520 - val_accuracy: 0.7312
Epoch 11/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5472 - accuracy: 0.7310 - val_loss: 0.5528 - val_accuracy: 0.7312
Epoch 12/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5472 - accuracy: 0.7317 - val_loss: 0.5517 - val_accuracy: 0.7305
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5468 - accuracy: 0.7320 - val_loss: 0.5507 - val_accuracy: 0.7279
Epoch 14/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5460 - accuracy: 0.7329 - val_loss: 0.5497 - val_accuracy: 0.7322
Epoch 15/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5454 - accuracy: 0.7316 - val_loss: 0.5504 - val_accuracy: 0.7328
Epoch 16/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5451 - accuracy: 0.7318 - val_loss: 0.5507 - val_accuracy: 0.7305
Epoch 17/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5447 - accuracy: 0.7322 - val_loss: 0.5502 - val_accuracy: 0.7285
Epoch 18/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5448 - accuracy: 0.7327 - val_loss: 0.5497 - val_accuracy: 0.7339
Epoch 19/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5440 - accuracy: 0.7339 - val_loss: 0.5499 - val_accuracy: 0.7292
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5435 - accuracy: 0.7324 - val_loss: 0.5512 - val_accuracy: 0.7269
Epoch 21/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5435 - accuracy: 0.7327 - val_loss: 0.5496 - val_accuracy: 0.7325
Epoch 22/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5434 - accuracy: 0.7325 - val_loss: 0.5488 - val_accuracy: 0.7321
Epoch 23/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5431 - accuracy: 0.7320 - val_loss: 0.5503 - val_accuracy: 0.7331
Epoch 24/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5423 - accuracy: 0.7341 - val_loss: 0.5512 - val_accuracy: 0.7257
Epoch 25/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5426 - accuracy: 0.7325 - val_loss: 0.5494 - val_accuracy: 0.7299
Epoch 26/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5423 - accuracy: 0.7331 - val_loss: 0.5509 - val_accuracy: 0.7292
Epoch 27/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5421 - accuracy: 0.7344 - val_loss: 0.5494 - val_accuracy: 0.7298
Epoch 28/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5420 - accuracy: 0.7341 - val_loss: 0.5499 - val_accuracy: 0.7307
Epoch 29/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5417 - accuracy: 0.7339 - val_loss: 0.5510 - val_accuracy: 0.7303
Epoch 30/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5415 - accuracy: 0.7346 - val_loss: 0.5492 - val_accuracy: 0.7307
Epoch 31/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5417 - accuracy: 0.7345 - val_loss: 0.5480 - val_accuracy: 0.7322
Epoch 32/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5412 - accuracy: 0.7355 - val_loss: 0.5500 - val_accuracy: 0.7326
Epoch 33/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5410 - accuracy: 0.7339 - val_loss: 0.5508 - val_accuracy: 0.7310
Epoch 34/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5411 - accuracy: 0.7369 - val_loss: 0.5499 - val_accuracy: 0.7320
Epoch 35/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5406 - accuracy: 0.7358 - val_loss: 0.5499 - val_accuracy: 0.7317
Epoch 36/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5402 - accuracy: 0.7350 - val_loss: 0.5524 - val_accuracy: 0.7262
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5408 - accuracy: 0.7353 - val_loss: 0.5502 - val_accuracy: 0.7314
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5403 - accuracy: 0.7352 - val_loss: 0.5501 - val_accuracy: 0.7320
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5401 - accuracy: 0.7348 - val_loss: 0.5512 - val_accuracy: 0.7307
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5403 - accuracy: 0.7349 - val_loss: 0.5491 - val_accuracy: 0.7333
Epoch 41/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5399 - accuracy: 0.7346 - val_loss: 0.5501 - val_accuracy: 0.7311
Epoch 42/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5399 - accuracy: 0.7362 - val_loss: 0.5506 - val_accuracy: 0.7315
Epoch 43/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5396 - accuracy: 0.7355 - val_loss: 0.5501 - val_accuracy: 0.7329
Epoch 44/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5395 - accuracy: 0.7363 - val_loss: 0.5510 - val_accuracy: 0.7318
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5395 - accuracy: 0.7372 - val_loss: 0.5511 - val_accuracy: 0.7296
Epoch 46/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5391 - accuracy: 0.7367 - val_loss: 0.5508 - val_accuracy: 0.7315
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5392 - accuracy: 0.7368 - val_loss: 0.5495 - val_accuracy: 0.7306
Epoch 48/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5390 - accuracy: 0.7364 - val_loss: 0.5508 - val_accuracy: 0.7305
Epoch 49/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5389 - accuracy: 0.7358 - val_loss: 0.5510 - val_accuracy: 0.7250
Epoch 50/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5391 - accuracy: 0.7363 - val_loss: 0.5517 - val_accuracy: 0.7287
Optimal number of epochs: 18

In [27]:
# reinstantiate the model, this time using the optimal hyperparameters and epochs
model2 = tuner.hypermodel.build(optimal_hps)
model2.fit(X_train_scaled, y_train, epochs=optimal_epoch, validation_data=(X_test_scaled,y_test))

Epoch 1/18
804/804 [==============================] - 8s 7ms/step - loss: 0.5799 - accuracy: 0.7141 - val_loss: 0.5629 - val_accuracy: 0.7229
Epoch 2/18
804/804 [==============================] - 4s 5ms/step - loss: 0.5590 - accuracy: 0.7264 - val_loss: 0.5585 - val_accuracy: 0.7264
Epoch 3/18
804/804 [==============================] - 5s 6ms/step - loss: 0.5557 - accuracy: 0.7276 - val_loss: 0.5575 - val_accuracy: 0.7292
Epoch 4/18
804/804 [==============================] - 4s 5ms/step - loss: 0.5536 - accuracy: 0.7287 - val_loss: 0.5561 - val_accuracy: 0.7300
Epoch 5/18
804/804 [==============================] - 4s 5ms/step - loss: 0.5517 - accuracy: 0.7296 - val_loss: 0.5562 - val_accuracy: 0.7289
Epoch 6/18
804/804 [==============================] - 5s 6ms/step - loss: 0.5511 - accuracy: 0.7308 - val_loss: 0.5531 - val_accuracy: 0.7293
Epoch 7/18
804/804 [==============================] - 4s 5ms/step - loss: 0.5504 - accuracy: 0.7299 - val_loss: 0.5538 - val_accuracy: 0.7297
Epoch 8/18
804/804 [==============================] - 4s 5ms/step - loss: 0.5489 - accuracy: 0.7291 - val_loss: 0.5526 - val_accuracy: 0.7317
Epoch 9/18
804/804 [==============================] - 5s 6ms/step - loss: 0.5485 - accuracy: 0.7291 - val_loss: 0.5512 - val_accuracy: 0.7311
Epoch 10/18
804/804 [==============================] - 5s 7ms/step - loss: 0.5478 - accuracy: 0.7306 - val_loss: 0.5527 - val_accuracy: 0.7317
Epoch 11/18
804/804 [==============================] - 5s 7ms/step - loss: 0.5474 - accuracy: 0.7297 - val_loss: 0.5520 - val_accuracy: 0.7301
Epoch 12/18
804/804 [==============================] - 3s 4ms/step - loss: 0.5467 - accuracy: 0.7318 - val_loss: 0.5531 - val_accuracy: 0.7278
Epoch 13/18
804/804 [==============================] - 3s 4ms/step - loss: 0.5466 - accuracy: 0.7314 - val_loss: 0.5507 - val_accuracy: 0.7271
Epoch 14/18
804/804 [==============================] - 3s 4ms/step - loss: 0.5461 - accuracy: 0.7313 - val_loss: 0.5496 - val_accuracy: 0.7282
Epoch 15/18
804/804 [==============================] - 3s 4ms/step - loss: 0.5458 - accuracy: 0.7324 - val_loss: 0.5507 - val_accuracy: 0.7335
Epoch 16/18
804/804 [==============================] - 3s 4ms/step - loss: 0.5453 - accuracy: 0.7315 - val_loss: 0.5498 - val_accuracy: 0.7319
Epoch 17/18
804/804 [==============================] - 4s 5ms/step - loss: 0.5449 - accuracy: 0.7326 - val_loss: 0.5507 - val_accuracy: 0.7308
Epoch 18/18
804/804 [==============================] - 4s 5ms/step - loss: 0.5445 - accuracy: 0.7321 - val_loss: 0.5508 - val_accuracy: 0.7313

In [31]:
# evaluate the model
eval_result = model2.evaluate(X_test_scaled, y_test)
print("[test loss, test accuracy]:", eval_result)

268/268 [==============================] - 1s 3ms/step - loss: 0.5508 - accuracy: 0.7313
[test loss, test accuracy]: [0.5507761836051941, 0.7313119769096375]

In [33]:
# Export our model to HDF5 file
model2.save("Models/attempt_3/AlphabetSoupCharity.h5")